language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
services:
  - memcached
  - redis-server
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
env:
  - PYTHONPATH=.
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-dev
  - sudo apt-get install -y python-matplotlib
  - sudo apt-get install -y libhdf5-serial-dev
  - sudo apt-get install -y libnetcdf-dev
install:
  - pip install -r ooiservices/requirements/dev.txt
before_script:
  - python ooiservices/manage.py deploy -p test
script:
  - python ooiservices/manage.py test --coverage
notifications:
    flowdock: 7728e9be2e099628ea6b3b0f489d2f9c
